FROM node:alpine3.18 AS builder

WORKDIR /app

COPY tetris-game/package*.json ./

RUN npm install

COPY tetris-game .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]