FROM node:lts AS development

ENV CI=true
ENV PORT=3000

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm ci
COPY . /app

CMD [ "npm", "start" ]

FROM development AS dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommands git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
username -aG docker vscode
EOF

# copy the previous image to the root directory so that don't have to
# build the same image again
# see this issue https://github.com/docker/awesome-compose/issues/401
COPY --from=gloursdocker/docker / /

FROM development AS builder

RUN npm run build

FROM nginx:1.13-alpine

COPY --from=builder /code/build /usr/share/nginx/html