name: react-go-postgres
services:
  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    networks:
      - client-side
    ports:
      - 3000:80
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: dockerfile
    environment:
      - DB_SOURCE=postgresql://root:root@db:5432/tetris-game?sslmode=disable
    networks:
      - client-side
      - server-side
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint: ["/app/wait-for.sh", "db:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tetris-game
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  ws:
    build:
      context: ws
      dockerfile: dockerfile
    ports:
      - 8081:8081

networks:
  client-side:
    driver: bridge
  server-side:
    driver: bridge

volumes:
  db-data:
