name: react-go-postgres
services:
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src:ro

  # TODO: start the server need to add wait-for to wait postgres start.   
  backend:
    build:
      context: backend
      target: development
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/tetris-game?sslmode=disable
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend:/app
      - backend-cache:/app/target
    depends_on:
      - db
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
  
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tetris-game
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}