version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tetris-game
    networks:
      - server-side
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  tetris-game:
    build:
      context: .
      dockerfile: dockerfile-development
    ports:
      - '8080:8080'
    networks:
      - server-side
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - postgres

networks:
  server-side: {}

volumes:
  db-data: {}