# Build stage
FROM golang:alpine3.19 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go

# RUN stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/main .
COPY ./app.env .

EXPOSE 8081
CMD [ "/app/main" ]