// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	Owner         string             `json:"owner"`
	AchievementID int32              `json:"achievement_id"`
	AchievedAt    pgtype.Timestamptz `json:"achieved_at"`
}

type Score struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Score     pgtype.Int8        `json:"score"`
	Level     pgtype.Int4        `json:"level"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Username          string             `json:"username"`
	HashedPassword    string             `json:"hashed_password"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
