// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, username string) error
	GetUser(ctx context.Context, username string) (User, error)
	ListScores(ctx context.Context, arg ListScoresParams) ([]Score, error)
	RankByLevel(ctx context.Context, arg RankByLevelParams) ([]Score, error)
	RankByScore(ctx context.Context, arg RankByScoreParams) ([]Score, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
